apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    labels:
      app: notification
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
