version: "3.8"
services:
    user-service:
        build: ./user-service
        ports:
            - "5000:5000"
        env_file:
            - ./user-service/.env
        volumes:
            - ./user-service:/app
            - /app/node_modules
        depends_on:
            - mongo
    product-service:
        build: ./product-service
        ports:
            - "5001:5001"
        env_file:
            - ./product-service/.env
        volumes:
            - ./product-service:/app
            - /app/node_modules
        depends_on:
            - mongo
    cart-service:
        build: ./cart-service
        ports:
            - "5002:5002"
        env_file:
            - ./cart-service/.env
        volumes:
            - ./cart-service:/app
            - /app/node_modules
        depends_on:
            - user-service
            - product-service
    order-service:
        build: ./order-service
        ports:
            - "5003:5003"
        env_file:
            - ./order-service/.env
        volumes:
            - ./order-service:/app
            - /app/node_modules
        depends_on:
            - user-service
            - product-service
            - cart-service
    payment-service:
        build: ./payment-service
        ports:
            - "5004:5004"
        env_file:
            - ./payment-service/.env
        volumes:
            - ./payment-service:/app
            - /app/node_modules
        depends_on:
            - user-service
            - product-service
            - cart-service
            - order-service
    notification-service:
        build: ./notification-service
        ports:
            - "5005:5005"
        env_file:
            - ./notification-service/.env
        volumes:
            - ./notification-service:/app
            - /app/node_modules
        depends_on:
            - user-service
            - product-service
            - cart-service
            - order-service
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
    nginx:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - user-service
            - product-service
            - cart-service
            - order-service
            - payment-service

volumes:
    mongo-data:
