apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  selector:
    labels:
      app: products
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
