apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    labels:
      app: payment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5006
      targetPort: 5006
