name: Build and Push Docker Images
on:
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5.0.0

      - name: Build Image
        run:
          "docker build ./user-sevice --tag ${{ secrets.DOCKER_USERNAME
          }}/user-service:latest"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest
